### ISSUE TITLE
arrayValue can be empty object

### ISSUE THREAD

**Issue by iSuslov** [jdbence/firestore-parser#1]
`arrayValue` not always has `values` field. So code can crash:

`
TypeError: Cannot read property 'map' of undefined
`

See line 12 of index.js

**Comment by jdbence** [comment]
@iSuslov Thanks for finding this case! Can you take a look at this PR if it solves what you are seeing? #2

**Comment by iSuslov** [comment]
LGTM. You acting so quickly, impressive! Nice and clean code btw. Thank you.
