### ISSUE TITLE
Nuxt and axios

### ISSUE THREAD

**Issue by andyfensham** [jdbence/firestore-parser#15]
I am trying to run this on nuxt and axios, and are getting the error that "response.json" is not a function. Please see my code below

`getRecords2(vuexContext, context) {
    let projectId = context.Firestore.projectId || process.env.projectId
    let url =
      process.env.fireStoreURL +
      'projects/' +
      projectId +
      '/databases/(default)/documents/' +
      context.Firestore.path
    const token = vuexContext.rootState.auth.token
    const config = {
      headers: { Authorization: `Bearer ${token}` }
    }
    this.$axios
      .$get(url, config)
      .then(response => response.json())
      .then(json => FireStoreParser(json))
      .then(json => console.log(json))
  }`

**Comment by jdbence** [comment]
I believe the Axios `get` method already returns the JSON so you should be able to remove `.then(response => response.json())`
