### ISSUE TITLE
Re Different Firestore result than the one in your example

### ISSUE THREAD

**Issue by andyfensham** [jdbence/firestore-parser#16]
I logged another call but I think it has nothing to do with axios but with the result I am getting back that need to be parsed.  My result is different from yours.

``
{
  "name": "projects/midrandchapel/databases/(default)/documents/about/lFFDPtq5T61BufAOBio0",
  "fields": {
    "actions": {
      "arrayValue": {
        "values": [
          {
            "mapValue": {
              "fields": {
                "text": {
                  "stringValue": "Contact Us"
                },
                "to": {
                  "stringValue": "/contact"
                },
                "color": {
                  "stringValue": "primary darken-4"
                }
              }
            }
          }
        ]
      }
    },
    "md": {
      "integerValue": "6"
    },
    "showimg": {
      "booleanValue": true
    },
    "cols": {
      "integerValue": "12"
    },
    "lg": {
      "integerValue": "3"
    },
    "subtitle": {
      "stringValue": "Subtitle or text goes here"
    },
    "xl": {
      "integerValue": "2"
    },
    "to": {
      "stringValue": "about/imnew"
    },
    "xs": {
      "integerValue": "12"
    },
    "text": {
      "stringValue": "text goes here"
    },
    "sm": {
      "integerValue": "12"
    },
    "srcavatar": {
      "stringValue": "https://picsum.photos/id/1005/50/50"
    },
    "title": {
      "stringValue": "I'm New"
    },
    "src": {
      "stringValue": "https://picsum.photos/id/1005/5760/3840"
    },
    "page": {
      "stringValue": "about"
    },
    "sortorder": {
      "integerValue": "0"
    }
  },
  "createTime": "2020-04-06T16:18:59.477042Z",
  "updateTime": "2020-04-08T05:55:02.021686Z"
}
``

**Comment by jdbence** [comment]
Looks like it's working properly.
Here is an **Repl.it** with your example
https://repl.it/repls/JointKaleidoscopicElement
