### ISSUE TITLE
mapValue does not have `fields` when empty

### ISSUE THREAD

**Issue by iSuslov** [jdbence/firestore-parser#5]
Hi! New bug report is here. When you have `"field_name": {}` in your database, it translates to `mapValue: {}` in REST response, so does not have `fields` field, which is expected in your code when parsing `mapValue`.

As a result we have "unidentified" passed into `getFireStoreProp` function and crash.

**Comment by jdbence** [comment]
@iSuslov Can you take a look at #6 PR?

**Comment by nyambe** [comment]
Hello, first of all, great parser!  The issue with empty fields is still happening.  Here I have an example

"arrayValue": {}

Its an empty slider field ! I was going mad because it worked an other calls.                ```
 "Slider": {
                  "arrayValue": {}
                },

Hope it helps

```
